# Generated by Django 3.1.6 on 2021-05-27 14:34

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='subjectName', unique_with=('subjectName', 'currentYear__year')),
        ),
    ]
