# Generated by Django 3.1.6 on 2021-05-28 10:50

import autoslug.fields
from django.db import migrations
import study.models.subjectExamRecord_model


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20210527_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectexamrecord',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='okay', editable=False, populate_from=study.models.subjectExamRecord_model.mixSlugExamRecord, unique='subject'),
            preserve_default=False,
        ),
    ]
