# Generated by Django 3.1.6 on 2021-06-19 05:38

import autoslug.fields
from django.db import migrations
import study.models.subject_model


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_subjectexamrecord_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'permissions': (('publish_subject', 'Can publish Subject'),)},
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=study.models.subject_model.mixSlugSubject, unique_with=('subjectName', 'currentYear__year')),
        ),
    ]
