# Generated by Django 3.1.6 on 2021-05-03 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examName', models.CharField(max_length=20, verbose_name='Exam Name')),
                ('examDate', models.DateField(verbose_name='Exam Date')),
                ('standard', models.PositiveIntegerField(default=11, validators=[django.core.validators.MinValueValidator(11), django.core.validators.MaxValueValidator(12)], verbose_name='Standard')),
                ('subject', models.CharField(choices=[('English', 'English'), ('Physic', 'Physic'), ('Chemistry', 'Chemistry'), ('Maths', 'Maths'), ('Biology', 'Biology'), ('Computer', 'Computer')], max_length=20, verbose_name='Subject')),
                ('slug', models.SlugField(help_text='A label for URL config.', unique=True)),
                ('syallbus', models.CharField(max_length=250, verbose_name='Syallbus')),
                ('marks', models.IntegerField(verbose_name='Total Marks')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Description')),
                ('resultPublished', models.BooleanField(default=False, verbose_name='Result Published')),
                ('taken', models.BooleanField(default=False, verbose_name='Exam Taken')),
            ],
            options={
                'ordering': ['-examDate'],
                'permissions': (('publish_exam', 'Can publish new Exams'),),
            },
        ),
    ]
