# Generated by Django 3.1.6 on 2021-03-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('English', 'English'), ('Physic', 'Physic'), ('Chemistry', 'Chemistry'), ('Maths', 'Maths'), ('Biology', 'Biology'), ('Computer', 'Computer')], max_length=20, verbose_name='Subject')),
                ('slug', models.SlugField(help_text='A label for URL config.', unique=True)),
                ('syallbus', models.CharField(max_length=140, verbose_name='Syallbus')),
                ('examDate', models.DateTimeField(verbose_name='Exam Date')),
                ('marks', models.IntegerField(verbose_name='Total Marks')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Description')),
                ('examName', models.CharField(max_length=20, verbose_name='Exam Name')),
                ('resultPublished', models.BooleanField(default=False, verbose_name='Result Published')),
            ],
            options={
                'ordering': ['-examDate'],
            },
        ),
    ]
