# Generated by Django 3.1.6 on 2021-05-28 10:18

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='examName', unique=True),
        ),
    ]
