# Generated by Django 3.1.6 on 2021-03-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='examDate',
            field=models.DateField(verbose_name='Exam Date'),
        ),
    ]
