# Generated by Django 3.1.6 on 2021-04-06 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0002_auto_20210328_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-examDate'], 'permissions': (('publish_exam', 'Can publish new Exams'),)},
        ),
    ]
