#EXAM DETAILS CELL
D0_NOT_MODIFY_CELL = 'E2:F3'
D0_NOT_MODIFY_START_COL = 4
DETAILS_TITLE = 'E5:F6'

#SUB-EXAM DETAILS 
DETAILS_START_ROW = 8
DETAILS_START_COL = 4

#MARK DETAILS CELL
ROLL_NUMBER_HEADER_ROW = 0
ROLL_NUMBER_START_ROW = 1
ROLL_NUMBER_START_COL = 0