# Generated by Django 3.1.6 on 2021-05-27 13:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50, verbose_name='Full Name')),
                ('slug', models.SlugField(help_text='A label for URL config.', unique=True)),
                ('rollNumber', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Roll Number')),
                ('std', models.PositiveIntegerField(default=11, validators=[django.core.validators.MinValueValidator(11), django.core.validators.MaxValueValidator(12)], verbose_name='Standard')),
                ('div', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1, verbose_name='Divison')),
                ('emailId', models.EmailField(max_length=30, null=True, unique=True, verbose_name='Student Email Id')),
                ('parentEmailId', models.EmailField(max_length=30, unique=True, verbose_name='Parent Email Id')),
                ('admissionYear', models.CharField(max_length=4, verbose_name='Admission Year')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'ordering': ['rollNumber'],
                'unique_together': {('rollNumber', 'std', 'div')},
            },
        ),
        migrations.CreateModel(
            name='SubjectMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalMarks', models.IntegerField(default=0, verbose_name='Total Marks')),
                ('totalExam', models.IntegerField(default=0, verbose_name='Total Exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.subject')),
            ],
            options={
                'ordering': ['student', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthDate', models.DateField(verbose_name='Birth Date')),
                ('slug', models.SlugField(help_text='A label for URL config.', unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1, verbose_name='Gender')),
                ('phoneNumber', models.CharField(max_length=12, unique=True, verbose_name='Phone Number')),
                ('previousSchool', models.CharField(blank=True, max_length=50, null=True, verbose_name='Previous School')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='A label for URL config.', unique=True)),
                ('fatherName', models.CharField(max_length=40, verbose_name='Father Name')),
                ('motherName', models.CharField(max_length=40, verbose_name='Mother Name')),
                ('fatherBussiness', models.CharField(max_length=30, verbose_name='Father Bussiness')),
                ('motherBussiness', models.CharField(blank=True, max_length=30, null=True, verbose_name='Mother Bussiness')),
                ('fatherStudy', models.CharField(blank=True, max_length=20, null=True, verbose_name='Father Education')),
                ('motherStudy', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mother Education')),
                ('phoneNumber', models.CharField(max_length=12, unique=True, verbose_name='Parent Phone Number')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalMarks', models.IntegerField(default=0, verbose_name='Total Marks')),
                ('totalExam', models.IntegerField(default=0, verbose_name='Total Exam')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('subjectmarks', models.ManyToManyField(related_name='academic', to='student.SubjectMarks')),
            ],
            options={
                'ordering': ['student'],
            },
        ),
    ]
