# Generated by Django 3.1.6 on 2021-05-21 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
        ('student', '0002_auto_20210419_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalMarks', models.IntegerField(default=0, verbose_name='Total Marks')),
                ('totalExam', models.IntegerField(default=0, verbose_name='Total Exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.subject')),
            ],
            options={
                'ordering': ['student', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='AcademicProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalMarks', models.IntegerField(default=0, verbose_name='Total Marks')),
                ('totalExam', models.IntegerField(default=0, verbose_name='Total Exam')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('subjectmarks', models.ManyToManyField(related_name='academic', to='student.SubjectMarks')),
            ],
            options={
                'ordering': ['student'],
            },
        ),
    ]
