# Generated by Django 3.1.6 on 2021-05-28 10:50

import autoslug.fields
from django.db import migrations
import student.models.academicProfile_model
import student.models.parentProfile_model
import student.models.studentProfile_model


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210528_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicprofile',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=student.models.academicProfile_model.mixAcademicProfile, unique_with=('student',)),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=student.models.parentProfile_model.mixSlugParentProfile, unique_with=('student',)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=student.models.studentProfile_model.mixSlugProfile, unique='student'),
        ),
    ]
