# Generated by Django 3.1.6 on 2021-06-19 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210528_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['rollNumber'], 'permissions': (('manage_student', 'Can manages Student'),), 'verbose_name': 'Student'},
        ),
    ]
